"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Put = exports.Post = exports.Get = exports.Delete = exports.ContextServices = exports.ContextController = exports.kernel = void 0;
var kernel_1 = require("./start/kernel");
Object.defineProperty(exports, "kernel", { enumerable: true, get: function () { return kernel_1.kernel; } });
var Router_1 = require("./Bin/Router");
Object.defineProperty(exports, "ContextController", { enumerable: true, get: function () { return Router_1.ContextController; } });
Object.defineProperty(exports, "ContextServices", { enumerable: true, get: function () { return Router_1.ContextServices; } });
Object.defineProperty(exports, "Delete", { enumerable: true, get: function () { return Router_1.Delete; } });
Object.defineProperty(exports, "Get", { enumerable: true, get: function () { return Router_1.Get; } });
Object.defineProperty(exports, "Post", { enumerable: true, get: function () { return Router_1.Post; } });
Object.defineProperty(exports, "Put", { enumerable: true, get: function () { return Router_1.Put; } });
